### ISSUE TITLE
V2.0 ToDo

### ISSUE THREAD

**Issue by Crossedfall** [crossedfall/crossed-cogs#2]
- [ ] Create helpers to make the actual cogs smaller and to make status checks faster and more reliable
- [ ] Enable linking between discord and BYOND
- [ ] Admin specific commands
- [ ] Player specific commands
- [ ] More round/player stats!
- [ ] Actually refactor the data handler to remove excessive checks

Current player specific command ideas:

- Show different results when normal users lookup ckeys vs when admins lookup ckeys. (hide identifiable information like IPs and CIDs when normal players use the command)
- Influence rounds based on discord commands. Similar to how some games have twitch chat interactions. 

Current admin specific command ideas:

- Restart/end the round
- Make global announcements
